Wrapper
calidae/normandy-vue pull request #11
Opened 2017-09-08 12:47 UTC by xevops

Cal tenir en compte que aquest pull request té dependencia del pull request wrapper-flush fet a normandy-css per tenir disponibles els estils corresponents al modificador flush de l'objecte

2017-09-08 13:37 UTC, afontcu reviewed
LGTM! només dues xorrades:

`wrappered` ---> `wrapped`

al Wrapper.vue hi ha 6 espais abans de `<slot>`, haurien de ser 4.

2017-09-08 15:52 UTC, oriolfg approved these changes

2017-09-10 16:09 UTC, xevops commented
Done!

2017-09-12 07:14 UTC, afontcu reviewed
Cal canviar la classe del CSS...i la classe del template 🙄  🙈 

![captura de pantalla 2017-09-12 a les 9 14 42](https://user-images.githubusercontent.com/9197791/30312686-dc12614e-979a-11e7-95b1-d7435807d9e1.png)

2017-11-03 16:27 UTC, xevops commented
Pensava que ja estava tancat això! En fi crec que ara ja està tot arreglat!!

2017-11-03 18:06 UTC, afontcu requested changes

2017-11-03 18:06 UTC, afontcu commented on src/components/Wrapper/Wrapper.test.js
> +describe('Cover.vue', () => {
oju aquí Cover.vue -> Wrapper.vue

2017-11-04 09:15 UTC, afontcu approved these changes

2017-11-04 09:17 UTC, merged